# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Pocket Pantry' do
  pod 'youtube-ios-player-helper'
  pod 'AFNetworking'
  pod 'GradientView'
  pod 'Alamofire'
  pod 'RealmSwift'
end
